
DROP TABLE IF EXISTS Resultat;
DROP TABLE IF EXISTS Specialisation;
DROP TABLE IF EXISTS Responsabilite;
DROP TABLE IF EXISTS Paiement;
DROP TABLE IF EXISTS Inscription;
DROP TABLE IF EXISTS Epreuve;
DROP TABLE IF EXISTS Financement;
DROP TABLE IF EXISTS Membre;
DROP TABLE IF EXISTS Specialite;
DROP TABLE IF EXISTS Discipline;
DROP TABLE IF EXISTS CompetitionExterne;
DROP TABLE IF EXISTS CompetitionInterne;
DROP TABLE IF EXISTS Competition;
DROP TABLE IF EXISTS OrganisateurExterne;
DROP TABLE IF EXISTS Activite;